server:
  port: 10000
spring:
  application:
    name: robot-server
logging:
  config: classpath:config/logback.xml
fan-yu:
  hardware-control:
    host: 192.168.1.22
    port: 8080
    timeout: 2
    request-command-config-file: E:/monkey/product/config/RequestCommandCache
    receive-command-config-file: E:/monkey/product/config/ReceiveCommandCache
  large-model:
    url: http://192.168.1.14:8017/add